version: "3"
services:
    build:
        build: ./maven
        volumes:
            - files:/root/webapps
    db:
        image: postgres
        #image: mariadb:10.1
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=secret
            #- MYSQL_ROOT_PASSWORD=secret
    prod:
        image: tomcat:7
        ports:
            - "8080:8080"
        volumes:
            - files:/usr/local/tomcat/webapps

volumes:
  files:


