version: "3"
services:
    build:
        build: ./maven
        volumes:
            - files:/root/webapps
    db:
        image: mariadb:10.1
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=secret
    prod:
        image: tomcat:7
        #image: tomcat:6.0.43
        ports:
            - "8080:8080"
        volumes:
            - files:/usr/local/tomcat/webapps

volumes:
  files:


